/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/developer-room.glb 
Author: saadhesham626 (https://sketchfab.com/saadhesham626)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/programmer-desk-setup-stylized-3d-room-ede58cf414534e47b57bf788dc075b17
Title: Programmer Desk Setup – Stylized 3D Room
*/

import React, { useRef, useMemo, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export default function DeveloperRoomModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/developer-room.glb')
  const { actions } = useAnimations(animations, group)

  // Glow materials for button states
  const activeMat = useMemo(() => new THREE.MeshStandardMaterial({
    color: "#fbbf24",
    emissive: "#fbbf24",
    emissiveIntensity: 3.5,
    toneMapped: false
  }), []);

  const hoverMat = useMemo(() => new THREE.MeshStandardMaterial({
    color: "#c084fc",
    emissive: "#c084fc",
    emissiveIntensity: 2.5,
    toneMapped: false
  }), []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_217" position={[2.538, 1.368, -2.949]} scale={0.381}>
                <mesh name="Object_369" geometry={nodes.Object_369.geometry} material={materials['SVGMat.017_15']} />
              </group>
              <group name="Empty009_313" position={[1.437, 1.734, -2.237]}>
                <group name="Cylinder013_308" position={[-0.142, -0.399, -0.053]} rotation={[-1.573, 0, Math.PI]} scale={[-0.036, 0.366, 0.037]}>
                  <mesh name="Object_515" geometry={nodes.Object_515.geometry} material={materials['Material.024']} />
                  <mesh name="Object_516" geometry={nodes.Object_516.geometry} material={materials.Base} />
                  <mesh name="Object_517" geometry={nodes.Object_517.geometry} material={materials['azul.001']} />
                  <mesh name="Object_518" geometry={nodes.Object_518.geometry} material={materials['Material.025']} />
                </group>
                <group name="Empty007_310" position={[-0.133, -0.425, 0.297]} rotation={[-Math.PI, 0, -0.805]} scale={[-0.281, 0.281, 0.281]}>
                  <group name="Circle004_309" position={[-0.006, 0.022, 3.029]} rotation={[-Math.PI / 2, 1.22, -Math.PI]}>
                    <mesh name="Object_521" geometry={nodes.Object_521.geometry} material={materials['Material.024']} />
                  </group>
                </group>
                <group name="Empty008_312" position={[-0.133, -0.387, 0.311]} rotation={[-Math.PI, 0, -0.805]} scale={[-0.281, 0.281, 0.281]}>
                  <group name="Circle003_311" position={[-0.006, 0.022, 0]} rotation={[Math.PI / 2, -1.072, 0]} scale={0.89}>
                    <mesh name="Object_524" geometry={nodes.Object_524.geometry} material={materials['Material.024']} />
                  </group>
                </group>
              </group>
              <group name="Robot_Origin_318" position={[0, 0.615, 0]} rotation={[-Math.PI / 2, 0, 3.078]} scale={0.569} />
              <group name="Mouth_320" position={[5.089, 3.273, 2.127]} rotation={[-Math.PI / 2, 0, 3.078]} />
              <group name="Wave_321" position={[0, 0, 1]} rotation={[-Math.PI / 2, 0, 3.078]} />
              <group name="Wave002_322" position={[0, 0, 0.427]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.474]} />
              <group name="Wave001_323" position={[0, 0, 0.819]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.834]} />
              <group name="Wave003_324" position={[0, 0, 0.05]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[1, 1, 0.128]} />
              <group name="Ears_325" position={[5.071, 3.498, 2.413]} scale={0.569} />
              <group name="Plane_0" position={[3.448, 3.267, 2.526]} rotation={[1.882, 0, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['SVGMat.017']} />
              </group>
              <group name="screen001_1" position={[0.354, 2.989, 2.592]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Black_Matt.001']} />
              </group>
              <group name="screen002_2" position={[1.463, 5.561, 3.36]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.918}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Base} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['SVGMat.017_0']} />
              </group>
              <group name="screen005_4" position={[1.582, 5.562, 3.36]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.918}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Base} />
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['SVGMat.017_0']} />
              </group>
              <group name="Room_5" position={[0.761, 0.242, -0.201]} scale={[1.06, 1.055, 1.06]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.049']} />
              </group>
              <group name="topedge_6" position={[2.852, 7.202, 3.616]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.metal} />
              </group>
              <group name="side_edge_7" position={[-2.952, 7.022, -4.531]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.metal} />
              </group>
              <group name="right_side_cube_8" position={[-2.749, 0.771, -4.494]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.metal} />
              </group>
              <group name="wifi_base_side_9" position={[-2.72, 7.924, 2.097]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.metal} />
              </group>
              <group name="wifi_extra_side_10" position={[-2.693, 8.139, 1.221]} rotation={[3.142, -Math.PI / 2, 0]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.metal} />
              </group>
              <group name="topedge001_11" position={[-3.032, 7.629, -2.349]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.metal} />
              </group>
              <group name="right_side_border_12" position={[4.724, 2.434, 3.624]} rotation={[-Math.PI, 0, 0]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.metal} />
              </group>
              <group name="Cube001_13" position={[5.045, 0.756, 3.474]} rotation={[0, -1.557, 0]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.metal} />
              </group>
              <group name="led_left_top_14" position={[-2.951, 7.591, -0.783]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 0.948]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.light} />
              </group>
              <group name="right_lde_15" position={[-1.706, 7.419, 3.477]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.085']} />
              </group>
              <group name="base_16" position={[-3.096, 0.59, -4.769]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.metal} />
              </group>
              <group name="heart_container_17" position={[-2.819, 0.623, -4.811]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.metal} />
              </group>
              <group name="icons_right_container_18" position={[0.666, 0.646, -4.548]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.metal} />
              </group>
              <group name="hexa_19" position={[-0.82, 0.638, -5.115]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.050']} />
              </group>
              <group name="Cube003_20" position={[5.214, 0.544, 3.049]} scale={[1, 1.563, 1]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.light} />
              </group>
              <group name="heart_21" position={[2.058, 0.63, -5.053]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.044']} />
              </group>
              <group name="Cube002_22" position={[-2.782, 0.588, -5.078]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.light} />
              </group>
              <group name="star_23" position={[-0.817, 0.672, -5.161]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.045']} />
              </group>
              <group name="Cube009_25" position={[4.176, 0.438, -2.935]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.042']} />
              </group>
              <group name="Cylinder_26" position={[0.823, 0.668, -5.057]} rotation={[1.571, 0.011, -0.002]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.047']} />
              </group>
              <group name="Cube005_27" position={[-2.943, 6.387, -4.799]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.light} />
              </group>
              <group name="Cube006_28" position={[-2.943, 1.436, -4.81]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.light} />
              </group>
              <group name="Cube010_29" position={[5.114, 5.825, 3.633]} rotation={[-Math.PI, 0, 0]} scale={[-0.23, -1, -1]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.043']} />
              </group>
              <group name="Cube011_30" position={[5.144, 5.212, 3.633]} rotation={[-Math.PI, 0, 0]} scale={[-0.227, -1, -1]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.light} />
              </group>
              <group name="wifi-signal_31" position={[-2.668, 8.409, 1.101]} rotation={[1.57, -0.009, -1.562]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.048']} />
              </group>
              <group name="Cube008_32" position={[-0.133, 0.845, -5.15]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.light} />
              </group>
              <group name="Cube012_33" position={[-0.133, 0.576, -5.111]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.light} />
              </group>
              <group name="Cube013_34" position={[-1.851, 2.593, 2.386]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Base} />
              </group>
              <group name="screen_holder_35" position={[0.521, 3.067, 2.566]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Base} />
              </group>
              <group name="keyboard_mouse_40" position={[0.605, 2.621, 2.264]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <group name="KEYBOARD_EXPobjcleanermaterialmergergles_39" position={[0.221, 0.025, 0]}>
                  <group name="Object_2_36" position={[0, -0.211, 0.039]} scale={0.837}>
                    <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.light} />
                  </group>
                  <group name="Object_3_37" position={[0, -0.211, 0.039]} scale={0.837}>
                    <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.Base} />
                  </group>
                  <group name="Object_4_38" position={[0.122, -0.253, 0.027]} scale={0.684}>
                    <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Base} />
                  </group>
                </group>
              </group>
              <group name="root_77" position={[2.579, 2.593, 2.544]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="GLTF_SceneRootNode_76" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="Cylinder001_1_46" position={[0.035, 0.479, 0.074]} rotation={[0.178, -0.076, -0.035]}>
                    <group name="Object_10_41">
                      <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_6_42">
                      <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_7_43">
                      <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_8_44">
                      <mesh name="Object_91_1" geometry={nodes.Object_91_1.geometry} material={materials['Material.004']} />
                    </group>
                    <group name="Object_9_45">
                      <mesh name="Object_93_1" geometry={nodes.Object_93_1.geometry} material={materials['Material.005']} />
                    </group>
                  </group>
                  <group name="Cylinder002_2_49" position={[0.069, 0.437, 0.042]} rotation={[-0.014, -0.178, -0.092]}>
                    <group name="Object_12_47">
                      <mesh name="Object_96_1" geometry={nodes.Object_96_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_13_48">
                      <mesh name="Object_98_1" geometry={nodes.Object_98_1.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="Cylinder003_3_52" position={[-0.008, 0.442, 0.077]} rotation={[0.178, -0.076, -0.035]}>
                    <group name="Object_15_50">
                      <mesh name="Object_101_1" geometry={nodes.Object_101_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_16_51">
                      <mesh name="Object_103_1" geometry={nodes.Object_103_1.geometry} material={materials['Material.059']} />
                    </group>
                  </group>
                  <group name="Cylinder004_4_55" position={[0.071, 0.493, -0.019]} rotation={[-0.236, -0.312, -0.33]}>
                    <group name="Object_18_53">
                      <mesh name="Object_106_1" geometry={nodes.Object_106_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_19_54">
                      <mesh name="Object_108_1" geometry={nodes.Object_108_1.geometry} material={materials['Material.064']} />
                    </group>
                  </group>
                  <group name="Cylinder005_5_58" position={[0.04, 0.393, -0.048]} rotation={[-0.29, -0.557, -0.049]}>
                    <group name="Object_21_56">
                      <mesh name="Object_111_1" geometry={nodes.Object_111_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_22_57">
                      <mesh name="Object_113_1" geometry={nodes.Object_113_1.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="Cylinder006_6_61" position={[-0.042, 0.479, -0.071]} rotation={[-0.217, 0.038, -0.042]}>
                    <group name="Object_24_59">
                      <mesh name="Object_116_1" geometry={nodes.Object_116_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_25_60">
                      <mesh name="Object_118_1" geometry={nodes.Object_118_1.geometry} material={materials['Material.012']} />
                    </group>
                  </group>
                  <group name="Cylinder007_7_67" position={[-0.066, 0.52, 0.042]} rotation={[0.069, 0.072, 0.171]}>
                    <group name="Object_27_62">
                      <mesh name="Object_121_1" geometry={nodes.Object_121_1.geometry} material={materials['Material.062']} />
                    </group>
                    <group name="Object_28_63">
                      <mesh name="Object_123_1" geometry={nodes.Object_123_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_29_64">
                      <mesh name="Object_125_1" geometry={nodes.Object_125_1.geometry} material={materials['Material.004']} />
                    </group>
                    <group name="Object_30_65">
                      <mesh name="Object_127_1" geometry={nodes.Object_127_1.geometry} material={materials['Material.005']} />
                    </group>
                    <group name="Object_31_66">
                      <mesh name="Object_129_1" geometry={nodes.Object_129_1.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="Cylinder008_8_73" position={[0.018, 0.495, -0.08]} rotation={[-0.176, -0.032, 0.078]}>
                    <group name="Object_33_68">
                      <mesh name="Object_132_1" geometry={nodes.Object_132_1.geometry} material={materials['Material.065']} />
                    </group>
                    <group name="Object_34_69">
                      <mesh name="Object_134_1" geometry={nodes.Object_134_1.geometry} material={materials.material_0} />
                    </group>
                    <group name="Object_35_70">
                      <mesh name="Object_136_1" geometry={nodes.Object_136_1.geometry} material={materials['Material.004']} />
                    </group>
                    <group name="Object_36_71">
                      <mesh name="Object_138_1" geometry={nodes.Object_138_1.geometry} material={materials['Material.005']} />
                    </group>
                    <group name="Object_37_72">
                      <mesh name="Object_140_1" geometry={nodes.Object_140_1.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="Cylinder_0_75" position={[0, 0.354, 0]}>
                    <group name="Object_4001_74">
                      <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.Base} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="right_side_border003_78" position={[0.428, 3.839, 3.183]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.material_0} />
              </group>
              <group name="right_side_border004_79" position={[0.428, 3.839, 3.183]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material_0} />
              </group>
              <group name="right_side_border006_80" position={[3.041, 3.839, 2.886]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.Base} />
              </group>
              <group name="Cube_81" position={[2.996, 2.541, 2.455]}>
                <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.light} />
              </group>
              <group name="Cube014_82" position={[-2.706, 6.034, -2.357]}>
                <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.Base} />
              </group>
              <group name="Cube015_83" position={[-3.24, 4.35, -2.386]}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.Base} />
              </group>
              <group name="Circle001_84" position={[1.975, 2.759, 1.772]} rotation={[0, 0.562, 0]} scale={0.248}>
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.Base} />
              </group>
              <group name="Sketchfab_model_133" position={[0.607, 2.734, 2.263]} rotation={[-Math.PI / 2, 0, -3.14]} scale={0.139}>
                <group name="Figuresfbx_132" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="RootNode_131">
                    <group name="Gumi_Figure_92" position={[6.305, 0, 0]}>
                      <group name="Figure_bottom4_87">
                        <group name="Circle6_86" rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                          <group name="Circle6__0_85">
                            <mesh name="Object_165_1" geometry={nodes.Object_165_1.geometry} material={materials['SVGMat.017_1']} />
                          </group>
                        </group>
                      </group>
                      <group name="Gumi_91">
                        <group name="Gumiobj_1_90">
                          <group name="Gumiobj_1_ctr_gumh001_hitemalpha_1Material_0_88">
                            <mesh name="Object_169_1" geometry={nodes.Object_169_1.geometry} material={materials['SVGMat.017_2']} />
                          </group>
                          <group name="Gumiobj_1_test_lambert2_0_89">
                            <mesh name="Object_171_1" geometry={nodes.Object_171_1.geometry} material={materials['SVGMat.017_3']} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Hatsune_miku_Figure_99" position={[-6.195, 0, 0]}>
                      <group name="Circle002_94" rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                        <group name="Circle__0_93">
                          <mesh name="Object_175_1" geometry={nodes.Object_175_1.geometry} material={materials['SVGMat.017_1']} />
                        </group>
                      </group>
                      <group name="MikuFigure_98">
                        <group name="MikuFigureobj_1_97">
                          <group name="MikuFigureobj_1_test_test_alpha_0_95">
                            <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials['SVGMat.017_4']} />
                          </group>
                          <group name="MikuFigureobj_1_test_test_te_000_r1_0_96">
                            <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials['SVGMat.017_5']} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Kaito_Figure_107" position={[-3.695, 0, 0]}>
                      <group name="Figure_bottom_102">
                        <group name="Circle2_101" rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                          <group name="Circle2__0_100">
                            <mesh name="Object_186_1" geometry={nodes.Object_186_1.geometry} material={materials['SVGMat.017_1']} />
                          </group>
                        </group>
                      </group>
                      <group name="KaitoFigure_106">
                        <group name="KaitoFigureobj_1_105">
                          <group name="KaitoFigureobj_1_lambert2_0_103">
                            <mesh name="Object_190_1" geometry={nodes.Object_190_1.geometry} material={materials['SVGMat.017_6']} />
                          </group>
                          <group name="KaitoFigureobj_1_lambert2_0001_104" position={[18.591, 0.023, 6.574]} rotation={[Math.PI, -0.16, Math.PI]} scale={0.474}>
                            <mesh name="Object_192_1" geometry={nodes.Object_192_1.geometry} material={materials['SVGMat.017_6']} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Len_Figure_115" position={[1.305, 0, 0]}>
                      <group name="Figure_bottom2_110">
                        <group name="Circle4_109" rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                          <group name="Circle4__0_108">
                            <mesh name="Object_197_1" geometry={nodes.Object_197_1.geometry} material={materials['SVGMat.017_1']} />
                          </group>
                        </group>
                      </group>
                      <group name="LenFigure_114">
                        <group name="LenFigureobj_1_113">
                          <group name="LenFigureobj_1_ren_s004_algha_0_111">
                            <mesh name="Object_201_1" geometry={nodes.Object_201_1.geometry} material={materials['SVGMat.017_7']} />
                          </group>
                          <group name="LenFigureobj_1_ren_s4_0_112">
                            <mesh name="Object_203_1" geometry={nodes.Object_203_1.geometry} material={materials['SVGMat.017_8']} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Meiko_Figure_122" position={[3.805, 0, 0]}>
                      <group name="Figure_bottom3_118">
                        <group name="Circle5_117" rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                          <group name="Circle5__0_116">
                            <mesh name="Object_208_1" geometry={nodes.Object_208_1.geometry} material={materials['SVGMat.017_1']} />
                          </group>
                        </group>
                      </group>
                      <group name="MeikoFigure_121">
                        <group name="MeikoFigureobj_1_120">
                          <group name="MeikoFigureobj_1_meiko_all_0_119">
                            <mesh name="Object_212_1" geometry={nodes.Object_212_1.geometry} material={materials['SVGMat.017_9']} />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Rin_Figure_130" position={[-1.195, 0, 0]}>
                      <group name="Figure_bottom1_125">
                        <group name="Circle3_124" position={[0.032, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.763}>
                          <group name="Circle3__0_123">
                            <mesh name="Object_217_1" geometry={nodes.Object_217_1.geometry} material={materials['SVGMat.017_1']} />
                          </group>
                        </group>
                      </group>
                      <group name="RinFigure_129">
                        <group name="RinFigureobj_1_128">
                          <group name="RinFigureobj_1_rin_S003_Alpha_0_126">
                            <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials['SVGMat.017_10']} />
                          </group>
                          <group name="RinFigureobj_1_rin_S003_Diffuse_0_127">
                            <mesh name="Object_223_1" geometry={nodes.Object_223_1.geometry} material={materials['SVGMat.017_11']} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model001_139" position={[2.429, 2.751, 2.03]} rotation={[-Math.PI / 2, 0, 3.097]} scale={1.836}>
                <group name="357e8906e1ed4020b649e447185dae7cfbx_138" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                  <group name="RootNode001_137">
                    <group name="Headphone_stand_v2_136" rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
                      <group name="Body1_135" scale={10}>
                        <group name="Body1_Carbon_Fiber_-_Twill_0_134" position={[-14.947, -6.146, -0.616]} rotation={[0, 0, -0.016]} scale={1.216}>
                          <mesh name="Object_230_1" geometry={nodes.Object_230_1.geometry} material={materials.Base} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model002_142" position={[2.755, 2.725, 1.943]} rotation={[-Math.PI / 2, 0, 0]} scale={0.584}>
                <group name="Headphones_finalobjcleanermaterialmergergles_141">
                  <group name="Object_2001_140" position={[-0.077, 0.15, 0.4]} rotation={[-0.121, 0.001, -0.12]} scale={0.724}>
                    <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['SVGMat.017_12']} />
                  </group>
                </group>
              </group>
              <group name="Curve_145" position={[-2.906, 5.887, 1.397]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.761, 0.761, 0.796]}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.007']} />
              </group>
              <group name="Curve002_146" position={[-2.875, 5.911, 1.407]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.761, 0.761, 0.796]}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Curve001_147" position={[-2.84, 5.39, 2.231]} rotation={[Math.PI / 2, 0, 1.574]} scale={[-0.83, 0.83, 0.83]}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.010']} />
              </group>
              <group name="Curve004_148" position={[-2.818, 5.426, 2.247]} rotation={[Math.PI / 2, 0, 1.574]} scale={[-0.83, 0.83, 0.83]}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Curve003_149" position={[-3.008, 5.365, 0.597]} rotation={[Math.PI / 2, 0, -1.572]} scale={0.784}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.011']} />
              </group>
              <group name="Curve006_150" position={[-2.989, 5.372, 0.58]} rotation={[Math.PI / 2, 0, -1.572]} scale={0.784}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Curve005_151" position={[-3.029, 4.971, 1.432]} rotation={[2.695, 0, -Math.PI / 2]} scale={[1.475, 1.5, 1.475]}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.014']} />
              </group>
              <group name="Curve007_152" position={[-2.938, 4.386, 2.201]} rotation={[Math.PI / 2, 0, -1.553]} scale={1.068}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Curve008_153" position={[-2.938, 4.386, 2.198]} rotation={[Math.PI / 2, 0, -1.553]} scale={1.068}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.020']} />
              </group>
              <group name="Curve009_154" position={[-2.94, 4.419, 2.289]} rotation={[Math.PI / 2, 0, -1.553]} scale={1.068}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.019']} />
              </group>
              <group name="Curve010_155" position={[-3, 4.027, 1.495]} rotation={[Math.PI / 2, 0, -1.462]} scale={[0.818, 1.654, 0.803]}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.003']} />
              </group>
              <group name="Curve011_156" position={[-2.967, 3.744, 1.348]} rotation={[Math.PI / 2, 0, -1.462]} scale={[0.818, 1.654, 0.803]}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.002']} />
              </group>
              <group name="Curve013_157" position={[-3.002, 4.865, 0.117]} rotation={[Math.PI / 2, 0, -1.653]} scale={[1.413, 1.874, 1.413]}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.015']} />
              </group>
              <group name="Curve014_158" position={[1.339, 10.175, -1.031]} rotation={[Math.PI / 2, 0, 0]} scale={2.74}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Curve015_159" position={[-3.019, 4.721, -0.068]} rotation={[Math.PI / 2, 0, -1.548]} scale={[1.136, 1.508, 1.136]}>
                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.016']} />
              </group>
              <group name="Curve012_160" position={[-2.943, 4.498, 0.63]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.716, 1.284, 0.716]}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.017']} />
              </group>
              <group name="Curve016_161" position={[-2.943, 4.498, 0.628]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.716, 1.284, 0.716]}>
                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Cylinder004_162" position={[1.965, 3.005, 1.795]} rotation={[Math.PI, -1.106, Math.PI]} scale={0.145}>
                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['SVGMat.017_13']} />
              </group>
              <group name="Cube016_163" position={[1.99, 3.052, 2.29]} rotation={[-Math.PI, -0.321, -Math.PI]} scale={[0.101, 0.101, 0.078]}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.Base} />
              </group>
              <group name="test_164" position={[1.943, 3.048, 2.19]} rotation={[Math.PI / 2, 0, 2.821]} scale={[0.135, 0.023, 0.135]}>
                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.light} />
              </group>
              <group name="test001_165" position={[1.944, 3.051, 2.177]} rotation={[Math.PI / 2, 0, 2.821]} scale={[0.11, 0.019, 0.11]}>
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.067']} />
              </group>
              <group name="Cube017_166" position={[-0.736, 2.985, 2.277]} rotation={[-Math.PI, 0.62, -Math.PI]} scale={[0.101, 0.101, 0.078]}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.Base} />
              </group>
              <group name="test002_167" position={[-0.682, 2.981, 2.181]} rotation={[Math.PI / 2, 0, -2.521]} scale={[0.135, 0.023, 0.135]}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.light} />
              </group>
              <group name="test003_168" position={[-0.671, 2.984, 2.173]} rotation={[Math.PI / 2, 0, -2.521]} scale={[0.11, 0.019, 0.11]}>
                <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.067']} />
              </group>
              <group name="Cylinder015_169" position={[-3.005, 4.014, 1.382]} rotation={[-0.055, 0, -Math.PI / 2]} scale={[0.605, 0.23, 0.605]}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.Base} />
              </group>
              <group name="Cube020_170" position={[-1.593, 3.367, 1.297]} rotation={[-Math.PI, 0.485, -Math.PI]} scale={[0.333, 0.08, 0.08]}>
                <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.032']} />
              </group>
              <group name="fan_171" position={[-1.523, 3.363, 1.115]} rotation={[-Math.PI, 0.485, -Math.PI]} scale={[0.185, 0.062, 0.023]}>
                <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.030']} />
              </group>
              <group name="Cube024_172" position={[-1.639, 3.476, -1.91]} rotation={[-1.505, 1.211, 1.5]} scale={[0.223, 0.223, 0.17]}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.061']} />
              </group>
              <group name="Plane005_173" position={[-2.877, 6.49, -3.535]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['SVGMat.017_6']} />
              </group>
              <group name="Plane008_174" position={[-2.424, 6.475, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.material_0} />
              </group>
              <group name="Plane011_175" position={[-2.864, 6.477, -3.292]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.002']} />
              </group>
              <group name="Plane012_176" position={[-2.424, 6.475, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.material_0} />
              </group>
              <group name="Plane013_177" position={[-2.85, 6.463, -3.049]} rotation={[2.861, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['SVGMat.017_1']} />
              </group>
              <group name="Plane016_178" position={[-2.929, 6.51, -3.047]} rotation={[2.861, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.material_0} />
              </group>
              <group name="Plane017_179" position={[-2.836, 6.448, -2.804]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.Base} />
              </group>
              <group name="Plane020_180" position={[-2.424, 6.397, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials.material_0} />
              </group>
              <group name="Plane021_181" position={[-2.822, 6.472, -2.544]} rotation={[-3.046, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.004']} />
              </group>
              <group name="Plane024_182" position={[-2.424, 6.625, -3.781]} rotation={[-3.046, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.material_0} />
              </group>
              <group name="Plane025_183" position={[-2.808, 6.448, -2.317]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['SVGMat.017_2']} />
              </group>
              <group name="Plane028_184" position={[-2.424, 6.387, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.material_0} />
              </group>
              <group name="Plane031_185" position={[-2.794, 6.484, -2.073]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['SVGMat.017_12']} />
              </group>
              <group name="Plane032_186" position={[-2.424, 6.396, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials.material_0} />
              </group>
              <group name="Plane033_187" position={[-2.78, 6.477, -1.829]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.005']} />
              </group>
              <group name="Plane036_188" position={[-2.424, 6.378, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials.material_0} />
              </group>
              <group name="Plane037_189" position={[-2.767, 6.488, -1.586]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Material.032']} />
              </group>
              <group name="Plane040_190" position={[-2.424, 6.376, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials.material_0} />
              </group>
              <group name="Plane041_191" position={[-2.753, 6.495, -1.342]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials.azul} />
              </group>
              <group name="Plane044_192" position={[-2.424, 6.371, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials.material_0} />
              </group>
              <group name="Plane045_193" position={[-2.739, 6.488, -1.098]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['SVGMat.017_0']} />
              </group>
              <group name="Plane048_194" position={[-2.424, 6.352, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials.material_0} />
              </group>
              <group name="Plane049_195" position={[-2.725, 6.45, -0.855]} rotation={[2.906, -0.057, 1.555]} scale={[0.318, 0.359, 0.08]}>
                <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['SVGMat.017_14']} />
              </group>
              <group name="Plane052_196" position={[-2.804, 6.446, -0.854]} rotation={[2.906, -0.057, 1.555]} scale={[0.318, 0.359, 0.08]}>
                <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials.material_0} />
              </group>
              <group name="Sketchfab_model003_205" position={[-1.733, 2.926, 0.194]} rotation={[-Math.PI / 2, 0, 0.401]} scale={0.178}>
                <group name="Cubeobjcleanermaterialmergergles_204">
                  <group name="Object_2002_197">
                    <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials.Base} />
                  </group>
                  <group name="Object_3001_198">
                    <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Material.028']} />
                  </group>
                  <group name="Object_4002_199">
                    <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials.Rojo} />
                  </group>
                  <group name="Object_5_200">
                    <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials.material_0} />
                  </group>
                  <group name="Object_6001_201">
                    <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials.material_0} />
                  </group>
                  <group name="Object_7001_202">
                    <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials.naranja} />
                  </group>
                  <group name="Object_8001_203">
                    <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials.verde} />
                  </group>
                </group>
              </group>
              <group name="Plane001_206" position={[-2.739, 6.488, -1.098]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.material_0} />
              </group>
              <group name="Plane003_207" position={[-2.424, 6.371, -3.801]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.material_0} />
              </group>
              <group name="Plane004_208" position={[-1.852, 2.828, -0.296]} rotation={[-1.546, 0.132, 3.097]} scale={[0.383, 0.242, 0.051]}>
                <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.material_0} />
              </group>
              <group name="Plane006_209" position={[-1.845, 2.826, -0.35]} rotation={[-1.546, 0.132, 3.097]} scale={[0.383, 0.242, 0.051]}>
                <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Material.035']} />
              </group>
              <group name="Sketchfab_model004_216" position={[0, -13.221, -1.294]} rotation={[-Math.PI / 2, 0, 0]} scale={0.163}>
                <group name="718cfe4bf2d546d1aba2b17f49e24f91objcleanermaterialmergergle_215">
                  <group name="Object_2003_214" position={[3.096, -7.711, 93.015]} rotation={[0, 0, 0.862]} scale={0.182}>
                    <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Material.068']} />
                    <mesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials['Material.041']} />
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model006_220" position={[2.475, 1.38, -2.404]} rotation={[-Math.PI / 2, 0, 0]} scale={0.683}>
                <group name="SleepiingCatobjcleanermaterialmergergles_219">
                  <group name="Object_2004_218" position={[0.839, -3.363, -0.465]} rotation={[0, 0, 1.089]}>
                    <mesh name="Object_373" geometry={nodes.Object_373.geometry} material={materials['SVGMat.017_14']} />
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model005_225" position={[0.513, 5.305, 3.545]} rotation={[-Math.PI / 2, 0, 0]} scale={0.995}>
                <group name="root002_224">
                  <group name="GLTF_SceneRootNode004_223" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Vert_1_222" rotation={[0, 0, 0.008]} scale={[1, 1, 1.349]}>
                      <group name="Object_4003_221" position={[-0.11, -0.01, 0.059]} rotation={[-Math.PI, 0, -3.125]} scale={1.092}>
                        <mesh name="Object_379" geometry={nodes.Object_379.geometry} material={materials['Material.053']} />
                        <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Material.046']} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Plane007_226" position={[-2.963, 9.598, -5.891]} rotation={[-Math.PI, -0.005, -Math.PI / 2]} scale={0.417}>
                <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Material.037']} />
              </group>
              <group name="Plane009_227" position={[-2.963, 8.328, -5.891]} rotation={[-Math.PI, -0.005, -Math.PI / 2]} scale={0.317}>
                <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.light} />
              </group>
              <group name="Plane010_228" position={[-2.969, 8.912, -6.98]} rotation={[-Math.PI, -0.005, -Math.PI / 2]} scale={0.344}>
                <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Material.022']} />
              </group>
              <group name="Plane014_229" position={[6.412, 9.009, 3.437]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.332}>
                <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Material.039']} />
              </group>
              <group name="Plane015_230" position={[6.412, 8.206, 3.437]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.265}>
                <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Material.040']} />
              </group>
              <group name="Plane018_231" position={[-2.979, 2.907, -5.886]} rotation={[-Math.PI, -0.132, -Math.PI / 2]} scale={0.457}>
                <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.light} />
              </group>
              <group name="Plane019_232" position={[-2.979, 1.517, -5.886]} rotation={[-Math.PI, -0.132, -Math.PI / 2]} scale={0.347}>
                <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Material.022']} />
              </group>
              <group name="Plane022_233" position={[-3.136, 2.156, -7.069]} rotation={[-Math.PI, -0.132, -Math.PI / 2]} scale={0.377}>
                <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Material.027']} />
              </group>
              <group name="Plane023_234" position={[-2.954, 8.912, -4.888]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.344}>
                <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Material.027']} />
              </group>
              <group name="Sketchfab_model007_237" position={[-1.367, 7.628, 0.193]} rotation={[-Math.PI / 2, 0, 1.829]} scale={0.981}>
                <group name="mail_iconobjcleanermaterialmergergles_236">
                  <group name="Object_3002_235" position={[1.934, 1.409, -2.809]} rotation={[-0.411, 0.105, -0.25]} scale={0.206}>
                    <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['SVGMat.017_16']} />
                    <mesh name="Object_403" geometry={nodes.Object_403.geometry} material={materials['Material.056']} />
                  </group>
                </group>
              </group>
              <group name="Plane026_238" position={[0.484, 3.999, 2.534]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.795, 1.551, 0.825]}>
                <mesh name="Object_405" geometry={nodes.Object_405.geometry} material={materials.Material_63} />
              </group>
              <group name="Plane027_239" position={[-1.479, 3.545, -1.888]} rotation={[1.595, 0.422, -1.482]} scale={[1, 0.968, 0.666]}>
                <mesh name="Object_407" geometry={nodes.Object_407.geometry} material={materials.material_0} />
              </group>
              <group name="Cube025_240" position={[2.908, 3.921, 2.879]} scale={[0.383, 1.282, 0.14]}>
                <mesh name="Object_409" geometry={nodes.Object_409.geometry} material={materials.light} />
              </group>
              <group name="Cube026_241" position={[-2.206, 3.921, 3.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.228, 1.282, 0.092]}>
                <mesh name="Object_411" geometry={nodes.Object_411.geometry} material={materials.Base} />
              </group>
              <group name="Plane029_242" position={[-2.915, 6.477, -3.779]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials['Material.066']} />
              </group>
              <group name="Plane034_243" position={[-2.915, 6.477, -3.779]} rotation={[3.092, -0.057, 1.555]} scale={[0.319, 0.359, 0.082]}>
                <mesh name="Object_415" geometry={nodes.Object_415.geometry} material={materials.material_0} />
              </group>
              <group name="Cube028_244" position={[2.703, 3.045, 1.876]} rotation={[-Math.PI, 0, 0]} scale={[0.034, 0.297, 0.03]}>
                <mesh name="Object_417" geometry={nodes.Object_417.geometry} material={materials.light} />
              </group>
              <group name="Sketchfab_model008_249" position={[-3.083, 1.705, -8.505]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root001_248">
                  <group name="GLTF_SceneRootNode001_247" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Curve012_0_246" position={[-0.055, 2.945, 6.336]} rotation={[Math.PI / 2, 0, 0]} scale={28.364}>
                      <group name="Object_4004_245" position={[0.003, -0.007, -0.008]} rotation={[0.011, 0.37, -1.539]} scale={0.825}>
                        <mesh name="Object_423" geometry={nodes.Object_423.geometry} material={materials.glossy_putih} />
                        <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials.material_0} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model009_255" position={[-3.256, 4.82, -3.555]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.313, 1.06, 0.313]}>
                <group name="root003_254">
                  <group name="GLTF_SceneRootNode005_253" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Cube_0_251" position={[0, 0, 0.121]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.026, 1.088, 0.074]}>
                      <group name="Object_4005_250" position={[-0.167, 0.085, 0]} scale={1.138}>
                        <mesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['Material.072']} />
                        <mesh name="Object_431" geometry={nodes.Object_431.geometry} material={materials['SVGMat.017_1']} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Plane002_256" position={[3.088, 1.029, -0.233]} scale={1.186}>
                <mesh name="Object_433" geometry={nodes.Object_433.geometry} material={materials['SVGMat.017_17']} />
              </group>
              <group name="Plane030_257" position={[0.854, 1.005, -0.326]} rotation={[0, Math.PI / 2, 0]} scale={[3.864, 2.502, 3.807]}>
                <mesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials['SVGMat.017_18']} />
              </group>
              <group name="Cylinder005_258" position={[-2.756, 1.303, -1.932]} rotation={[0, 1.547, Math.PI / 2]} scale={[-0.052, -0.351, -0.052]}>
                <mesh name="Object_437" geometry={nodes.Object_437.geometry} material={materials['Material.075']} />
              </group>
              <group name="Cylinder006_259" position={[-2.127, 1.303, -2.11]} rotation={[-Math.PI, 1.127, -Math.PI / 2]} scale={[-0.052, -0.351, -0.052]}>
                <mesh name="Object_439" geometry={nodes.Object_439.geometry} material={materials['Material.075']} />
              </group>
              <group name="Sketchfab_model010_266" position={[2.37, 1.572, 1.189]} rotation={[-1.496, -0.075, 1.833]} scale={0.286}>
                <group name="Root_265">
                  <group name="25_surf0000_1_0_0_root_root_ground003_262" position={[0.269, -0.098, 0.04]} scale={16.713}>
                    <group name="25_surf0000_1_0_0_root_root_ground001_260" position={[-0.111, 0.143, -0.06]} rotation={[0.146, -0.061, 0.715]} scale={0.737}>
                      <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials['Material.082']} />
                      <mesh name="Object_445" geometry={nodes.Object_445.geometry} material={materials['Material.076']} />
                      <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.077']} />
                      <mesh name="Object_447" geometry={nodes.Object_447.geometry} material={materials['Material.078']} />
                      <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.079']} />
                      <mesh name="Object_449" geometry={nodes.Object_449.geometry} material={materials['Material.080']} />
                      <mesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.081']} />
                      <mesh name="Object_451" geometry={nodes.Object_451.geometry} material={materials['Material.083']} />
                      <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials['Material.084']} />
                    </group>
                    <group name="25_surf0000_1_0_0_root_root_ground008_261" position={[-0.111, 0.143, -0.06]} rotation={[0.146, -0.061, 0.715]} scale={0.737}>
                      <mesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials['Material.082']} />
                      <mesh name="Object_455" geometry={nodes.Object_455.geometry} material={materials['Material.076']} />
                      <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials['Material.077']} />
                      <mesh name="Object_457" geometry={nodes.Object_457.geometry} material={materials['Material.078']} />
                      <mesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials['Material.079']} />
                      <mesh name="Object_459" geometry={nodes.Object_459.geometry} material={materials['Material.080']} />
                      <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials['Material.081']} />
                      <mesh name="Object_461" geometry={nodes.Object_461.geometry} material={materials['Material.083']} />
                      <mesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials['Material.084']} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="Sketchfab_model011_273" position={[-1.683, 2.717, 2.447]} rotation={[-Math.PI / 2, 0, 1.756]} scale={0.075}>
                <group name="Figuresfbx001_272" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="RootNode002_271">
                    <group name="Gumi_Figure001_270" position={[6.305, 0, 0]}>
                      <group name="Gumi001_269">
                        <group name="Gumiobj_1001_268">
                          <group name="Gumiobj_1_test_lambert2_0001_267" position={[0.012, 2.168, 0.143]}>
                            <mesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials['SVGMat.017_3']} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Plane035_274" position={[-1.437, 3.405, 1.625]} rotation={[Math.PI / 2, 0, -1.102]} scale={[0.641, 0.814, 0.57]}>
                <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials['Material.030']} />
              </group>
              <group name="Cube035_275" position={[-1.756, 3.071, 1.583]} rotation={[-1.546, 0.047, -2.056]} scale={[0.438, 0.173, 0.076]}>
                <mesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials.azul} />
                <mesh name="Object_475" geometry={nodes.Object_475.geometry} material={materials.Base} />
              </group>
              <group name="Empty001_277" position={[-1.553, 3.687, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
                <group name="Cylinder009_276">
                  <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty002_279" position={[-1.553, 3.345, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
                <group name="Cylinder007_278">
                  <mesh name="Object_481" geometry={nodes.Object_481.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty003_281" position={[-1.553, 2.984, 1.17]} rotation={[0, -0.592, -2.972]} scale={[-0.068, 0.068, 0.068]}>
                <group name="Cylinder008_280">
                  <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty004_283" position={[-1.956, 3.087, 1.922]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
                <group name="Cylinder010_282">
                  <mesh name="Object_487" geometry={nodes.Object_487.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty005_285" position={[-1.764, 3.115, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
                <group name="Cylinder011_284">
                  <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty006_287" position={[-1.624, 3.082, 1.347]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.073, 0.073, 0.073]}>
                <group name="Cylinder012_286">
                  <mesh name="Object_493" geometry={nodes.Object_493.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Empty010_289" position={[-1.058, 2.815, 1.765]} rotation={[-1.637, -0.128, -0.035]}>
                <group name="Circle011_288">
                  <mesh name="Object_496" geometry={nodes.Object_496.geometry} material={materials['Material.051']} />
                  <mesh name="Object_497" geometry={nodes.Object_497.geometry} material={materials['Black_Matt.001']} />
                  <mesh name="Object_498" geometry={nodes.Object_498.geometry} material={materials['Material.023']} />
                  <mesh name="Object_499" geometry={nodes.Object_499.geometry} material={materials['Material.057']} />
                </group>
              </group>
              <group name="Cube004_290" position={[-2.133, 3.439, 1.682]} rotation={[Math.PI, -1.058, Math.PI]} scale={[-0.173, -0.217, -0.061]}>
                <mesh name="Object_501" geometry={nodes.Object_501.geometry} material={materials.Base} />
              </group>
              <group name="Empty012_292" position={[-2.093, 3.448, 1.703]} rotation={[3.133, -1.039, 1.859]} scale={[-0.102, 0.095, 0.097]}>
                <group name="Cylinder014_291">
                  <mesh name="Object_504" geometry={nodes.Object_504.geometry} material={materials.light} />
                </group>
              </group>
              <group name="Sketchfab_model012_298" position={[-2.348, 0.411, -4.55]} rotation={[-Math.PI / 2, 0, 1.521]} scale={0.043}>
                <group name="3bcd6dbcea8946b59b4ddf259507b6f0fbx_297" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="RootNode003_296">
                    <group name="Box002_294" position={[1.668, 54.594, 0]} scale={1.139}>
                      <group name="Box002_aguion_0_293" position={[-4.777, -10.964, 4.752]} rotation={[0, 0.644, 0]} scale={0.681}>
                        <mesh name="Object_510" geometry={nodes.Object_510.geometry} material={materials['SVGMat.017_19']} />
                        <mesh name="Object_511" geometry={nodes.Object_511.geometry} material={materials.Material_63_0} />
                        <mesh name="Object_512" geometry={nodes.Object_512.geometry} material={materials.Material_63_1} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="Plane038_329" position={[7.02, 6.611, 3.597]} rotation={[Math.PI / 2, 0, 0]} scale={[1.375, 1.473, 0.437]}>
                <mesh name="Object_533" geometry={nodes.Object_533.geometry} material={materials.Base} />
              </group>
              <group name="Plane039_330" position={[7.02, 5.281, 3.597]} rotation={[Math.PI / 2, 0, 0]} scale={[1.375, 1.473, 0.437]}>
                <mesh name="Object_535" geometry={nodes.Object_535.geometry} material={materials.Base} />
              </group>
              <group name="Plane042_331" position={[7.02, 3.927, 3.597]} rotation={[Math.PI / 2, 0, 0]} scale={[1.375, 1.473, 0.437]}>
                <mesh name="Object_537" geometry={nodes.Object_537.geometry} material={materials.Base} />
              </group>
              <group name="Plane043_332" position={[7.016, 2.536, 3.588]} rotation={[Math.PI / 2, 0, 0]} scale={[1.375, 1.473, 0.437]}>
                <mesh name="Object_539" geometry={nodes.Object_539.geometry} material={materials.Base} />
              </group>
              {/* SKILLS */}
              <group 
                name="Text001_333" 
                position={[7.377, 5.269, 3.385]} 
                rotation={[Math.PI / 2, -0.002, -Math.PI]} 
                scale={[0.637, 0.637, 0.779]}
                onClick={(e) => { e.stopPropagation(); props.onSectionClick('skills'); }}
                onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer'; props.onSectionHover('skills'); }}
                onPointerOut={(e) => { e.stopPropagation(); document.body.style.cursor = 'auto'; props.onSectionHover(null); }}
              >
                <mesh name="Object_541" geometry={nodes.Object_541.geometry} material={props.activeSection === 'skills' ? activeMat : (props.hoveredSection === 'skills' ? hoverMat : materials.light)} />
              </group>

              {/* ABOUT */}
              <group 
                name="Text002_334" 
                position={[7.126, 6.618, 3.412]} 
                rotation={[Math.PI / 2, -0.002, Math.PI]} 
                scale={0.728}
                onClick={(e) => { e.stopPropagation(); props.onSectionClick('about'); }}
                onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer'; props.onSectionHover('about'); }}
                onPointerOut={(e) => { e.stopPropagation(); document.body.style.cursor = 'auto'; props.onSectionHover(null); }}
              >
                <mesh name="Object_543" geometry={nodes.Object_543.geometry} material={props.activeSection === 'about' ? activeMat : (props.hoveredSection === 'about' ? hoverMat : materials.light)} />
              </group>

              {/* WORKS */}
              <group 
                name="Text003_335" 
                position={[7.187, 3.926, 3.432]} 
                rotation={[Math.PI / 2, -0.002, Math.PI]} 
                scale={0.709}
                onClick={(e) => { e.stopPropagation(); props.onSectionClick('works'); }}
                onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer'; props.onSectionHover('works'); }}
                onPointerOut={(e) => { e.stopPropagation(); document.body.style.cursor = 'auto'; props.onSectionHover(null); }}
              >
                <mesh name="Object_545" geometry={nodes.Object_545.geometry} material={props.activeSection === 'works' ? activeMat : (props.hoveredSection === 'works' ? hoverMat : materials.light)} />
              </group>

              {/* CONTACT */}
              <group 
                name="Text004_336" 
                position={[7.446, 2.541, 3.43]} 
                rotation={[Math.PI / 2, -0.002, Math.PI]} 
                scale={[0.498, 0.632, 0.692]}
                onClick={(e) => { e.stopPropagation(); props.onSectionClick('contact'); }}
                onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer'; props.onSectionHover('contact'); }}
                onPointerOut={(e) => { e.stopPropagation(); document.body.style.cursor = 'auto'; props.onSectionHover(null); }}
              >
                <mesh name="Object_547" geometry={nodes.Object_547.geometry} material={props.activeSection === 'contact' ? activeMat : (props.hoveredSection === 'contact' ? hoverMat : materials.light)} />
              </group>
              <group name="Sketchfab_model014_367" position={[5.098, 1.348, 2.59]} rotation={[-Math.PI / 2, 0, 2.641]} scale={0.698}>
                <group name="a45b6f53b9cc462a82863bb5898bf730fbx001_366" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                  <group name="Object_2006_365">
                    <group name="RootNode005_364">
                      <group name="Robot_Origin001_363" position={[0, 0.615, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <group name="Ears001_338" position={[0, 0, 2.967]}>
                          <group name="Ears_Black_Matt_0_337">
                            <mesh name="Object_555" geometry={nodes.Object_555.geometry} material={materials['Black_Matt.001']} />
                          </group>
                        </group>
                        <group name="Empty011_341" position={[0, -0.06, 2.786]}>
                          <group name="Eyes001_340" position={[0, -0.431, 0.076]}>
                            <group name="Eyes_Blue_Light_0_339">
                              <mesh name="Object_559" geometry={nodes.Object_559.geometry} material={materials['Blue_Light.001']} />
                            </group>
                          </group>
                        </group>
                        <group name="Hand_origin_344" position={[0.723, 0, 2.015]}>
                          <group name="hANDS001_343" position={[-0.723, 0, -1.963]}>
                            <group name="hANDS_White_Glossy_0_342">
                              <mesh name="Object_563" geometry={nodes.Object_563.geometry} material={materials['White_Glossy.001']} />
                            </group>
                          </group>
                        </group>
                        <group name="Hand_origin002_347" position={[-0.723, 0, 2.015]} rotation={[0, 0, -Math.PI]}>
                          <group name="hANDS003_346" position={[-0.723, 0, -1.963]}>
                            <group name="hANDS002_White_Glossy_0_345">
                              <mesh name="Object_567" geometry={nodes.Object_567.geometry} material={materials['White_Glossy.001']} />
                            </group>
                          </group>
                        </group>
                        <group name="Mouth001_349" position={[0, -0.504, 2.573]}>
                          <group name="Mouth_Blue_Light_0_348">
                            <mesh name="Object_570" geometry={nodes.Object_570.geometry} material={materials['Blue_Light.001']} />
                          </group>
                        </group>
                        <group name="Wave004_355" position={[0, 0, 1]}>
                          <group name="Wave_Blue_Light_0_354">
                            <mesh name="Object_580" geometry={nodes.Object_580.geometry} material={materials['Blue_Light.001']} />
                          </group>
                        </group>
                        <group name="Wave005_357" position={[0, 0, 0.427]} scale={[1, 1, 0.474]}>
                          <group name="Wave002_Blue_Light_0_356">
                            <mesh name="Object_583" geometry={nodes.Object_583.geometry} material={materials['Blue_Light.001']} />
                          </group>
                        </group>
                        <group name="Wave006_359" position={[0, 0, 0.819]} scale={[1, 1, 0.834]}>
                          <group name="Wave001_Blue_Light_0_358">
                            <mesh name="Object_586" geometry={nodes.Object_586.geometry} material={materials['Blue_Light.001']} />
                          </group>
                        </group>
                        <group name="Wave007_361" position={[0, 0, 0.05]} scale={[1, 1, 0.128]}>
                          <group name="Wave003_Blue_Light_0_360">
                            <mesh name="Object_589" geometry={nodes.Object_589.geometry} material={materials['Blue_Light.001']} />
                          </group>
                        </group>
                        <group name="Robot001_353" position={[0, 0, 0.051]}>
                          <group name="Robot_Black_Matt_0_350">
                            <mesh name="Object_573" geometry={nodes.Object_573.geometry} material={materials['Black_Matt.001']} />
                          </group>
                          <group name="Robot_Blue_Light_0_351">
                            <mesh name="Object_575" geometry={nodes.Object_575.geometry} material={materials['Blue_Light.001']} />
                          </group>
                          <group name="Robot_White_Glossy_0_352">
                            <mesh name="Object_577" geometry={nodes.Object_577.geometry} material={materials['White_Glossy.001']} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="GamingClutter_018_368" position={[-0.997, 0.129, -0.147]} rotation={[0.065, 0.213, 0.128]} scale={[0.8, 1.126, 1.034]}>
                <mesh name="Object_591" geometry={nodes.Object_591.geometry} material={materials.material_0} />
              </group>
              <group name="GamingClutter_005001_369" position={[-0.207, 0.098, 0.086]} rotation={[-2.836, 0.823, 2.7]} scale={[0.926, 0.827, 0.772]}>
                <mesh name="Object_593" geometry={nodes.Object_593.geometry} material={materials.material_0} />
              </group>
              <group name="GamingClutter_035001_370" position={[0.215, 0.122, -0.733]} rotation={[-0.214, -1.013, -0.083]} scale={[1.137, 0.655, 1.039]}>
                <mesh name="Object_595" geometry={nodes.Object_595.geometry} material={materials.material_0} />
              </group>
              <group name="Cube022_371" position={[-2.28, 3.963, 2.927]} scale={[0.383, 1.282, 0.14]}>
                <mesh name="Object_597" geometry={nodes.Object_597.geometry} material={materials.light} />
              </group>
              <group name="download_button_372" position={[-1.479, 3.195, -1.894]} rotation={[0.002, -0.029, 1.926]} scale={[-0.118, 0.438, 0.62]}>
                <mesh name="Object_599" geometry={nodes.Object_599.geometry} material={materials['Material.036']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/developer-room.glb')
