// Generates src/styles/springs.css. Run it after changing a spring:
//
//   npm run springs
//
// The output is committed, so a deploy never depends on this file having been
// run — same arrangement as scripts/build-fonts.py. tests/spring.test.js fails if
// the committed CSS has drifted from what the solver now produces, which is what
// stops the two from disagreeing silently.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { springEasing } from '../src/lib/spring.js';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The whole spring vocabulary of the site. Five, one per physical situation that
 * actually occurs — not five shades of the same feel.
 *
 * mass is 1 throughout: with only one moving object per spring there is nothing
 * to weigh it against, so stiffness and damping carry all the meaning and a
 * second free parameter would only make the numbers harder to compare.
 */
export const SPRINGS = {
  // Cards and pills lifting off the page. Stiff enough to feel like paper rather
  // than rubber, with about 3% overshoot — visible as life, not as a bounce.
  paper: { mass: 1, stiffness: 760, damping: 41 },

  // Buttons and icon controls. Same character, roughly a third quicker, because a
  // control that answers a click slower than ~200ms feels reluctant.
  snap: { mass: 1, stiffness: 1980, damping: 62 },

  // Small light things arriving at full size. Its own entry rather than a reuse
  // of `snap` for a reason worth writing down: the pills scale in from 0.86, so
  // the spring's overshoot is diluted by the travel — `snap`'s 4.7% of a 0.14
  // scale change is 0.7% of final size, which is not a pop by any measure. This
  // one is damped loosely enough that what lands on screen overshoots by ~2%.
  pop: { mass: 1, stiffness: 1480, damping: 38 },

  // The logo and the pinned sticker: decorative, so this one is allowed to
  // actually oscillate. It crosses its target three times before settling.
  wobble: { mass: 1, stiffness: 690, damping: 21 },

  // Content arriving. Exactly critically damped (damping = 2*sqrt(stiffness)),
  // which is the fastest a spring can arrive without ever passing its target.
  // Deliberate: text that overshoots its final position reads as a mistake, and
  // it is the one place on the site where overshoot is wrong.
  settle: { mass: 1, stiffness: 400, damping: 40 },
};

const solved = Object.entries(SPRINGS).map(([name, spring]) => [
  name,
  spring,
  springEasing(spring),
]);

const describe = (spring, out) => {
  const kind =
    out.zeta < 0.999 ? `underdamped, ζ=${out.zeta}` : out.zeta > 1.001 ? `overdamped, ζ=${out.zeta}` : 'critically damped';
  const overshoot =
    out.peak > 1 ? `${((out.peak - 1) * 100).toFixed(1)}% overshoot` : 'no overshoot';
  return `stiffness ${spring.stiffness}, damping ${spring.damping} — ${kind}, ${overshoot}, settles in ${out.ms}ms`;
};

export const buildSpringCss = () => {
  const body = solved
    .map(
      ([name, spring, out]) =>
        `  /* ${describe(spring, out)} */\n` +
        `  --spring-${name}: ${out.css};\n` +
        `  --spring-${name}-ms: ${out.ms}ms;`,
    )
    .join('\n\n');

  // The negative @supports, not a plain value before the linear() one. Custom
  // property values are not validated when they are parsed, so a fallback
  // declaration *above* a linear() declaration loses to it everywhere and then
  // fails at substitution time in the browsers it was meant to protect. Querying
  // the feature and overriding downward is the form that actually works.
  const fallback = Object.keys(SPRINGS)
    .map((name) => `    --spring-${name}: cubic-bezier(0.2, 0.8, 0.2, 1);`)
    .join('\n');

  return `/* Generated by scripts/springs.mjs — do not edit by hand.
   Run \`npm run springs\` instead. The curves are the sampled step response of a
   mass-spring-damper; the durations are the solver's settling times, and the two
   have to stay together because linear() is normalised to whatever duration it is
   played over. Parameters live in scripts/springs.mjs, the solver in
   src/lib/spring.js. */

:root {
${body}
}

/* Pre-2023 Safari and Firefox. Everything degrades to the curve the site used
   before the springs existed, which is a real ease-out — not to \`ease\`, which is
   what an unsupported linear() would otherwise fall back to. */
@supports not (transition-timing-function: linear(0, 1)) {
  :root {
${fallback}
  }
}
`;
};

export const springCssPath = join(here, '..', 'src', 'styles', 'springs.css');

// Only when run as a command. The test imports `buildSpringCss` to compare it
// against the committed file, and a write on import would make that comparison
// pass by definition.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(springCssPath, buildSpringCss(), 'utf8');

  for (const [name, spring, out] of solved) {
    console.log(`--spring-${name}  ${describe(spring, out)}, ${out.samples} stops`);
  }
  console.log(`\nwrote ${springCssPath}`);
}
