import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
// Both stylesheets are imported once, here, rather than by each page. Five pages
// importing the same file worked, but it meant the styles were tied to whichever
// page happened to load first — and src/index.css was a third copy of the reset
// that sketchbook.css already contains.
//
// fonts.css comes first so the @font-face rules are registered before any rule
// that names the family. It is generated by scripts/build-fonts.py; the files it
// points at live in public/fonts and are preloaded from index.html.
//
// springs.css declares nothing but custom properties. Order is not load-bearing
// here — var() resolves at computed-value time whatever sequence the sheets
// arrive in — but tokens read better above the rules that consume them. It is
// generated by scripts/springs.mjs from the solver in src/lib/spring.js.
import './styles/fonts.css'
import './styles/springs.css'
import './styles/sketchbook.css'
import App from './App.jsx'
import { enableReveal } from './lib/motion'

// Opts the document into scroll-reveal before the first paint, so revealed
// elements are never briefly visible and then hidden again.
enableReveal()

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
