import React, { useEffect, useState } from 'react';
import { Mail, ArrowRight, Send } from 'lucide-react';
import { FaGithub, FaLinkedin } from 'react-icons/fa';
import './sketchbook.css';

const SketchbookLayout = () => {
  const [mounted, setMounted] = useState(false);
  const [sketchPath, setSketchPath] = useState(null);

  useEffect(() => {
    setMounted(true);
    // Fetch the high-detail vectorized path generated by potrace
    fetch('/sketch-avatar.svg')
      .then(res => res.text())
      .then(text => {
        const match = text.match(/<path[^>]+d="([^"]+)"/i);
        if (match) {
          setSketchPath(match[1]);
        }
      })
      .catch(e => console.error("Error loading vector avatar", e));
  }, []);

  return (
    <div className="sketch-body">
      <div className="sketch-container">
        
        <header className="sketch-header">
          <div className="sketch-logo">Portfolio.</div>
          <nav className="sketch-nav">
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#skills">Skills</a>
            <a href="#certificates">Certificates</a>
            <a href="#projects">Work</a>
            <a href="#contact">Contact</a>
          </nav>
        </header>

        <section id="home" className="sketch-hero">
          <div className="sketch-hero-text">
            <span className="sketch-greeting">Hi, I am</span>
            <h1 className="sketch-title">Shreyash</h1>
            <h2 className="sketch-subtitle">Full Stack Developer & AI Engineer</h2>
            
            <p className="sketch-description">
              I build robust web applications and intelligent systems. 
              <br/>Currently available for freelance work and new opportunities!
            </p>

            <div style={{ display: 'flex', gap: '1.5rem', marginBottom: '2rem' }}>
              <a href="https://github.com/Iitian001" target="_blank" rel="noreferrer" style={{ color: 'var(--ink)' }}><FaGithub size={30} /></a>
              <a href="https://www.linkedin.com/in/shreyashautomation" target="_blank" rel="noreferrer" style={{ color: 'var(--ink)' }}><FaLinkedin size={30} /></a>
              <a href="mailto:shreyash.aiml.dev@gmail.com" style={{ color: 'var(--ink)' }}><Mail size={30} /></a>
            </div>

            <a href="#projects" className="sketch-btn">
              Explore Projects <ArrowRight size={24} />
            </a>
          </div>

          <div className="sketch-hero-visual">
            <div 
              className="sketch-avatar-container" 
              style={{ 
                position: 'relative', 
                border: 'none', 
                boxShadow: 'none',
                background: 'transparent',
                padding: '10px'
              }}
            >
              <style>{`
                @keyframes avatarFadeIn {
                  0% { opacity: 0; filter: blur(3px); }
                  100% { opacity: 1; filter: blur(0px); }
                }
                @keyframes paperFadeIn {
                  0% { opacity: 0; transform: scale(0.95); }
                  100% { opacity: 1; transform: scale(1); }
                }
              `}</style>
              
              {/* White backing card (Polaroid effect) */}
              <div style={{
                position: 'absolute',
                top: 0, left: 0, right: 0, bottom: 0,
                background: '#fff',
                borderRadius: '15px 225px 15px 255px/255px 15px 225px 15px',
                opacity: 0,
                animation: mounted ? 'paperFadeIn 0.5s cubic-bezier(0.2, 0.8, 0.2, 1) forwards' : 'none',
                animationDelay: '0.2s',
                boxShadow: '10px 10px 0px rgba(0,0,0,0.1)'
              }}></div>
              
              <img 
                src="/sketch-avatar.jpg" 
                alt="Shreyash" 
                className="sketch-avatar"
                style={{ 
                  opacity: 0, 
                  position: 'relative',
                  animation: mounted ? 'avatarFadeIn 1.5s cubic-bezier(0.2, 0.8, 0.2, 1) forwards' : 'none', 
                  animationDelay: '5s', // Fades in smoothly right as the pencil finishes drawing
                  zIndex: 5
                }} 
              />
              
              {sketchPath && (
                <svg 
                  viewBox="0 0 819 1024" // Matches the potrace output exactly
                  preserveAspectRatio="xMidYMid slice"
                  style={{ 
                    position: 'absolute', 
                    top: '10px', left: '10px', 
                    width: 'calc(100% - 20px)', height: 'calc(100% - 20px)', 
                    pointerEvents: 'none', 
                    zIndex: 10, 
                    overflow: 'hidden',
                    borderRadius: '255px 15px 225px 15px/15px 225px 15px 255px' // clip precisely to the image border
                  }}
                >
                  {/* The High-Detail Vector Line Art drawn stroke by stroke */}
                  <path 
                    d={sketchPath}
                    fill="none" 
                    stroke="var(--ink)" 
                    strokeWidth="3" 
                    strokeLinejoin="round"
                    strokeLinecap="round"
                    pathLength="1"
                    strokeDasharray="1"
                    strokeDashoffset="1"
                  >
                    <animate attributeName="stroke-dashoffset" from="1" to="0" dur="5.5s" fill="freeze" calcMode="linear" />
                    {/* Fade out the vector lines gracefully as the real image fades in behind it */}
                    <animate attributeName="opacity" values="1; 1; 0" keyTimes="0; 0.9; 1" dur="6s" fill="freeze" />
                  </path>
                  
                  {/* The animated pencil racing along the complex vector path */}
                  <g opacity="1">
                    <animateMotion 
                      dur="5.5s" 
                      fill="freeze" 
                      path={sketchPath}
                      calcMode="linear"
                    />
                    <animateTransform attributeName="transform" type="translate" values="0,0; 0,0; 50,100" keyTimes="0; 0.9; 1" dur="6s" fill="freeze" />
                    <animate attributeName="opacity" values="1; 1; 0" keyTimes="0; 0.95; 1" dur="6s" fill="freeze" />
                    
                    {/* Scaled up because the SVG viewBox is 819x1024 */}
                    <g transform="scale(5) rotate(35)">
                      <polygon points="0,0 -2,-12 2,-12" fill="#2c2c2c" /> {/* Lead */}
                      <polygon points="-2,-12 2,-12 6,-25 -6,-25" fill="#d4a373" /> {/* Wood */}
                      <rect x="-6" y="-60" width="12" height="35" fill="#2c2c2c" /> {/* Body */}
                      <rect x="-6" y="-68" width="12" height="8" fill="#d4af37" /> {/* Metal */}
                      <path d="M -6,-68 L -6,-72 Q 0,-78 6,-72 L 6,-68 Z" fill="#e76f51" /> {/* Eraser */}
                    </g>
                  </g>
                </svg>
              )}
            </div>
            <div className="sketch-arrow-annotation">
              That's me! &uarr;
            </div>
          </div>
        </section>

        {/* About Section */}
        <section id="about" style={{ marginTop: '8rem' }}>
          <h2 className="sketch-section-title">Who Am I?</h2>
          
          <div style={{ display: 'flex', gap: '4rem', alignItems: 'center', flexWrap: 'wrap' }}>
            <div className="sketch-box" style={{ flex: '1', fontSize: '1.6rem', lineHeight: '1.6' }}>
              <p style={{ margin: '0 0 1rem 0' }}>
                I'm Shreyash, a passionate creative developer specializing in building stunning, high-performance web applications and intelligent systems. 
              </p>
              <p style={{ margin: 0 }}>
                I blend bleeding-edge technology with bold, unapologetic design. When I'm not writing code or automating workflows, you can find me exploring new AI architectures or refining my design systems.
              </p>
            </div>
            <div className="sketch-box" style={{ flex: '0.6', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <h3 style={{ margin: 0, fontSize: '2rem', color: 'var(--marker-blue)' }}>Fast Facts</h3>
              <div style={{ fontSize: '1.4rem' }}><strong>Location:</strong> India</div>
              <div style={{ fontSize: '1.4rem' }}><strong>Email:</strong> shreyash.aiml.dev@gmail.com</div>
              <div style={{ fontSize: '1.4rem' }}><strong>Experience:</strong> Full Stack & AI</div>
              <div style={{ fontSize: '1.4rem' }}><strong>Status:</strong> Open to Work</div>
            </div>
          </div>
        </section>

        {/* Skills Section */}
        <section id="skills" style={{ marginTop: '8rem' }}>
          <h2 className="sketch-section-title">My Skills</h2>
          
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1.5rem', justifyContent: 'center', marginTop: '2rem' }}>
            {['React', 'JavaScript / TypeScript', 'Python', 'Machine Learning', 'AI Development', 'Workflow Automation', 'UI / UX Design', 'Node.js', 'Tailwind CSS'].map((skill, index) => (
              <div key={index} className="sketch-box" style={{ padding: '0.8rem 1.5rem', fontSize: '1.5rem', color: index % 2 === 0 ? 'var(--marker-blue)' : 'var(--marker-red)' }}>
                {skill}
              </div>
            ))}
          </div>
        </section>

        {/* Certificates Section */}
        <section id="certificates" style={{ marginTop: '8rem' }}>
          <h2 className="sketch-section-title">Certifications</h2>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', marginTop: '2rem', maxWidth: '800px', margin: '2rem auto 0' }}>
            
            <a href="https://learn.deeplearning.ai/certificates/2272a4ee-5c3e-4b27-95fd-b7bd70b0bd27" target="_blank" rel="noreferrer" className="sketch-box" style={{ display: 'flex', alignItems: 'center', gap: '2rem', padding: '1.5rem', textDecoration: 'none', color: 'black', transition: 'transform 0.2s' }}>
              <Star size={40} color="var(--marker-blue)" />
              <div>
                <h3 style={{ margin: 0, fontSize: '1.8rem', color: 'var(--marker-blue)' }}>Data Analytics Foundations</h3>
                <p style={{ margin: '0.5rem 0 0', fontSize: '1.4rem' }}>DeepLearning.AI</p>
              </div>
            </a>

            <a href="https://learn.deeplearning.ai/certificates/907381d1-8616-4b35-9eac-d588876d0d19" target="_blank" rel="noreferrer" className="sketch-box" style={{ display: 'flex', alignItems: 'center', gap: '2rem', padding: '1.5rem', textDecoration: 'none', color: 'black', transition: 'transform 0.2s' }}>
              <Star size={40} color="var(--marker-red)" />
              <div>
                <h3 style={{ margin: 0, fontSize: '1.8rem', color: 'var(--marker-red)' }}>Fast Prototyping of GenAI Apps with Streamlit</h3>
                <p style={{ margin: '0.5rem 0 0', fontSize: '1.4rem' }}>DeepLearning.AI</p>
              </div>
            </a>
            
          </div>
        </section>

        {/* Projects Section */}
        <section id="projects" style={{ marginTop: '8rem' }}>
          <h2 className="sketch-section-title">Things I've Built</h2>
          
          <div className="sketch-grid">
            
            {/* Project 1 */}
            <div className="sketch-box">
              <h3 className="sketch-project-title">Palak AI Stock Expert</h3>
              <div className="sketch-project-tech">AI / Data / Finance</div>
              <p className="sketch-project-desc">
                An advanced financial analytics dashboard that uses AI to provide actionable stock market insights and predictions.
              </p>
              <a href="https://github.com/Iitian001/Palak_Ai_stock-expert" target="_blank" rel="noreferrer" className="sketch-btn" style={{ padding: '0.4rem 1rem', fontSize: '1.2rem' }}>
                View Source <FaGithub size={16} />
              </a>
            </div>

            {/* Project 2 */}
            <div className="sketch-box">
              <h3 className="sketch-project-title">n8n Templates</h3>
              <div className="sketch-project-tech">Automation / Workflows</div>
              <p className="sketch-project-desc">
                A highly organized collection of ready-to-use n8n automation workflows designed to streamline complex business logic.
              </p>
              <a href="https://github.com/Iitian001/N8N_tamplets" target="_blank" rel="noreferrer" className="sketch-btn" style={{ padding: '0.4rem 1rem', fontSize: '1.2rem' }}>
                View Source <FaGithub size={16} />
              </a>
            </div>

            {/* Project 3 */}
            <div className="sketch-box">
              <h3 className="sketch-project-title">3D Portfolio</h3>
              <div className="sketch-project-tech">React / Three.js / WebGL</div>
              <p className="sketch-project-desc">
                An immersive 3D interactive web portfolio built to showcase creative development and complex rendering techniques.
              </p>
              <a href="https://shreyashmishra.in" target="_blank" rel="noreferrer" className="sketch-btn" style={{ padding: '0.4rem 1rem', fontSize: '1.2rem' }}>
                Live Site <ArrowRight size={16} />
              </a>
            </div>

            {/* Project 4 */}
            <div className="sketch-box">
              <h3 className="sketch-project-title">Shreyash Code</h3>
              <div className="sketch-project-tech">Python / Scripts</div>
              <p className="sketch-project-desc">
                A suite of powerful Python scripts utilized for data processing, automation, and backend system tasks.
              </p>
              <a href="https://github.com/Iitian001/Shreyash_code-" target="_blank" rel="noreferrer" className="sketch-btn" style={{ padding: '0.4rem 1rem', fontSize: '1.2rem' }}>
                View Source <FaGithub size={16} />
              </a>
            </div>

          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" style={{ marginTop: '8rem', marginBottom: '4rem' }}>
          <h2 className="sketch-section-title">Let's Talk</h2>
          
          <div className="sketch-box" style={{ maxWidth: '600px', margin: '0 auto', padding: '3rem' }}>
            <h3 style={{ fontSize: '2rem', marginTop: 0, marginBottom: '1rem', color: 'var(--ink)' }}>Send me a message</h3>
            <p style={{ fontSize: '1.4rem', marginBottom: '2rem' }}>Interested in collaborating or just want to say hi? Drop a message below.</p>
            
            <form action="https://api.web3forms.com/submit" method="POST" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
              <input type="hidden" name="access_key" value="32325e99-d553-4bad-a24a-50f938ffbd0c" />
              
              <input 
                type="text" 
                name="name" 
                placeholder="Your Name" 
                required 
                className="sketch-box"
                style={{ fontFamily: 'inherit', fontSize: '1.4rem', padding: '1rem', outline: 'none' }}
              />
              
              <input 
                type="email" 
                name="email" 
                placeholder="Your Email" 
                required 
                className="sketch-box"
                style={{ fontFamily: 'inherit', fontSize: '1.4rem', padding: '1rem', outline: 'none' }}
              />
              
              <textarea 
                name="message" 
                placeholder="What's on your mind?" 
                required 
                rows="4" 
                className="sketch-box"
                style={{ fontFamily: 'inherit', fontSize: '1.4rem', padding: '1rem', outline: 'none', resize: 'vertical' }}
              ></textarea>
              
              <button type="submit" className="sketch-btn" style={{ justifyContent: 'center', marginTop: '1rem', width: '100%' }}>
                Send It <Send size={20} />
              </button>
            </form>
          </div>
        </section>

        {/* Footer */}
        <footer className="sketch-footer">
          <div style={{ fontFamily: "'Caveat', cursive", fontSize: '2.5rem', color: 'var(--ink)' }}>Handcrafted by Shreyash</div>
          <div style={{ fontSize: '1.2rem', color: 'var(--ink-light)', marginTop: '0.5rem' }}>© 2026 All rights reserved</div>
        </footer>

      </div>
    </div>
  );
};

export default SketchbookLayout;
